# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from project.server import query_handler_pb2 as project_dot_server_dot_query__handler__pb2


class QueryHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryGraph = channel.unary_unary(
                '/QueryHandler/QueryGraph',
                request_serializer=project_dot_server_dot_query__handler__pb2.GraphArgs.SerializeToString,
                response_deserializer=project_dot_server_dot_query__handler__pb2.QueryResponse.FromString,
                )
        self.QueryPitchVector = channel.unary_unary(
                '/QueryHandler/QueryPitchVector',
                request_serializer=project_dot_server_dot_query__handler__pb2.VectorArgs.SerializeToString,
                response_deserializer=project_dot_server_dot_query__handler__pb2.QueryResponse.FromString,
                )


class QueryHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPitchVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryGraph,
                    request_deserializer=project_dot_server_dot_query__handler__pb2.GraphArgs.FromString,
                    response_serializer=project_dot_server_dot_query__handler__pb2.QueryResponse.SerializeToString,
            ),
            'QueryPitchVector': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPitchVector,
                    request_deserializer=project_dot_server_dot_query__handler__pb2.VectorArgs.FromString,
                    response_serializer=project_dot_server_dot_query__handler__pb2.QueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QueryHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QueryHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/QueryHandler/QueryGraph',
            project_dot_server_dot_query__handler__pb2.GraphArgs.SerializeToString,
            project_dot_server_dot_query__handler__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryPitchVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/QueryHandler/QueryPitchVector',
            project_dot_server_dot_query__handler__pb2.VectorArgs.SerializeToString,
            project_dot_server_dot_query__handler__pb2.QueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
