# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project/server/query_handler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='project/server/query_handler.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"project/server/query_handler.proto\"^\n\tGraphArgs\x12\x11\n\tquery_mid\x18\x01 \x01(\t\x12\x13\n\x0buse_minimum\x18\x02 \x01(\x08\x12\x14\n\x0cmelody_track\x18\x03 \x01(\x05\x12\x13\n\x0b\x63hord_track\x18\x04 \x01(\x05\"5\n\nVectorArgs\x12\x11\n\tquery_mid\x18\x01 \x01(\t\x12\x14\n\x0cmelody_track\x18\x02 \x01(\x05\"\x81\x01\n\rQueryResponse\x12,\n\x07ranking\x18\x01 \x03(\x0b\x32\x1b.QueryResponse.RankingEntry\x12\x12\n\nquery_time\x18\x02 \x01(\x01\x1a.\n\x0cRankingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32i\n\x0cQueryHandler\x12(\n\nQueryGraph\x12\n.GraphArgs\x1a\x0e.QueryResponse\x12/\n\x10QueryPitchVector\x12\x0b.VectorArgs\x1a\x0e.QueryResponseb\x06proto3'
)




_GRAPHARGS = _descriptor.Descriptor(
  name='GraphArgs',
  full_name='GraphArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_mid', full_name='GraphArgs.query_mid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_minimum', full_name='GraphArgs.use_minimum', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='melody_track', full_name='GraphArgs.melody_track', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chord_track', full_name='GraphArgs.chord_track', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=132,
)


_VECTORARGS = _descriptor.Descriptor(
  name='VectorArgs',
  full_name='VectorArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_mid', full_name='VectorArgs.query_mid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='melody_track', full_name='VectorArgs.melody_track', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=187,
)


_QUERYRESPONSE_RANKINGENTRY = _descriptor.Descriptor(
  name='RankingEntry',
  full_name='QueryResponse.RankingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='QueryResponse.RankingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='QueryResponse.RankingEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=319,
)

_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ranking', full_name='QueryResponse.ranking', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_time', full_name='QueryResponse.query_time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYRESPONSE_RANKINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=319,
)

_QUERYRESPONSE_RANKINGENTRY.containing_type = _QUERYRESPONSE
_QUERYRESPONSE.fields_by_name['ranking'].message_type = _QUERYRESPONSE_RANKINGENTRY
DESCRIPTOR.message_types_by_name['GraphArgs'] = _GRAPHARGS
DESCRIPTOR.message_types_by_name['VectorArgs'] = _VECTORARGS
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GraphArgs = _reflection.GeneratedProtocolMessageType('GraphArgs', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHARGS,
  '__module__' : 'project.server.query_handler_pb2'
  # @@protoc_insertion_point(class_scope:GraphArgs)
  })
_sym_db.RegisterMessage(GraphArgs)

VectorArgs = _reflection.GeneratedProtocolMessageType('VectorArgs', (_message.Message,), {
  'DESCRIPTOR' : _VECTORARGS,
  '__module__' : 'project.server.query_handler_pb2'
  # @@protoc_insertion_point(class_scope:VectorArgs)
  })
_sym_db.RegisterMessage(VectorArgs)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), {

  'RankingEntry' : _reflection.GeneratedProtocolMessageType('RankingEntry', (_message.Message,), {
    'DESCRIPTOR' : _QUERYRESPONSE_RANKINGENTRY,
    '__module__' : 'project.server.query_handler_pb2'
    # @@protoc_insertion_point(class_scope:QueryResponse.RankingEntry)
    })
  ,
  'DESCRIPTOR' : _QUERYRESPONSE,
  '__module__' : 'project.server.query_handler_pb2'
  # @@protoc_insertion_point(class_scope:QueryResponse)
  })
_sym_db.RegisterMessage(QueryResponse)
_sym_db.RegisterMessage(QueryResponse.RankingEntry)


_QUERYRESPONSE_RANKINGENTRY._options = None

_QUERYHANDLER = _descriptor.ServiceDescriptor(
  name='QueryHandler',
  full_name='QueryHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=321,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryGraph',
    full_name='QueryHandler.QueryGraph',
    index=0,
    containing_service=None,
    input_type=_GRAPHARGS,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QueryPitchVector',
    full_name='QueryHandler.QueryPitchVector',
    index=1,
    containing_service=None,
    input_type=_VECTORARGS,
    output_type=_QUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYHANDLER)

DESCRIPTOR.services_by_name['QueryHandler'] = _QUERYHANDLER

# @@protoc_insertion_point(module_scope)
